title: Storytelling Notes
author: Tony Hirst
copyright: "2022-2026" 
only_build_toc_files: true

execute:
  execute_notebooks: off
  timeout: 60  
parse:
  myst_dmath_double_inline: true

sphinx:
  config:
    html_copy_source: false
    html_theme: sphinx_book_theme
    html_baseurl: https://island-storynotes.montystoryteller.org/
    sitemap_url_scheme: "{link}"
    sitemap_locales: [null]

  extra_extensions:
    - sphinx_togglebutton
    - sphinx_sitemap
    - sphinxcontrib.youtube